# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"                                stop:0 #000000,  /*Top */\n"
"                                stop:0.5 #1C1B1A,   /* Center */\n"
"                                stop:1 #383633);       /* Buttom */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Liquid1 = QtWidgets.QProgressBar(self.centralwidget)
        self.Liquid1.setGeometry(QtCore.QRect(20, 170, 601, 71))
        self.Liquid1.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #000;\n"
"    border-radius: 5px;\n"
"    background-color: #E0E0E0; /* Neutral background */\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #42A5F5; /* Stat color */\n"
"    border-radius: 5px;\n"
"}")
        self.Liquid1.setMaximum(100)
        self.Liquid1.setProperty("value", 50)
        self.Liquid1.setTextVisible(False)
        self.Liquid1.setFormat("")
        self.Liquid1.setObjectName("Liquid1")
        self.lbl_Patient1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Patient1.setGeometry(QtCore.QRect(20, 70, 201, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Patient1.setFont(font)
        self.lbl_Patient1.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.lbl_Patient1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Patient1.setObjectName("lbl_Patient1")
        self.lbl_Patient1_DextroseWeight = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Patient1_DextroseWeight.setGeometry(QtCore.QRect(20, 110, 351, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Patient1_DextroseWeight.setFont(font)
        self.lbl_Patient1_DextroseWeight.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.lbl_Patient1_DextroseWeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Patient1_DextroseWeight.setObjectName("lbl_Patient1_DextroseWeight")
        self.lbl_Patient1_Percent = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Patient1_Percent.setGeometry(QtCore.QRect(630, 180, 101, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Patient1_Percent.setFont(font)
        self.lbl_Patient1_Percent.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.lbl_Patient1_Percent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Patient1_Percent.setObjectName("lbl_Patient1_Percent")
        self.Liquid1_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.Liquid1_2.setGeometry(QtCore.QRect(20, 380, 601, 71))
        self.Liquid1_2.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #000;\n"
"    border-radius: 5px;\n"
"    background-color: #E0E0E0; /* Neutral background */\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #42A5F5; /* Stat color */\n"
"    border-radius: 5px;\n"
"}")
        self.Liquid1_2.setMaximum(100)
        self.Liquid1_2.setProperty("value", 60)
        self.Liquid1_2.setTextVisible(False)
        self.Liquid1_2.setFormat("")
        self.Liquid1_2.setObjectName("Liquid1_2")
        self.lbl_Patient2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Patient2.setGeometry(QtCore.QRect(20, 280, 201, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Patient2.setFont(font)
        self.lbl_Patient2.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.lbl_Patient2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Patient2.setObjectName("lbl_Patient2")
        self.lbl_Patient2_DextroseWeight = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Patient2_DextroseWeight.setGeometry(QtCore.QRect(20, 320, 371, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Patient2_DextroseWeight.setFont(font)
        self.lbl_Patient2_DextroseWeight.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.lbl_Patient2_DextroseWeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Patient2_DextroseWeight.setObjectName("lbl_Patient2_DextroseWeight")
        self.lbl_Patient2_Percent = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Patient2_Percent.setGeometry(QtCore.QRect(630, 390, 101, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Patient2_Percent.setFont(font)
        self.lbl_Patient2_Percent.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.lbl_Patient2_Percent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Patient2_Percent.setObjectName("lbl_Patient2_Percent")
        self.lbl_Title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Title.setGeometry(QtCore.QRect(230, 10, 291, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Title.setFont(font)
        self.lbl_Title.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.lbl_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Title.setObjectName("lbl_Title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Patient1.setText(_translate("MainWindow", "Patient 1"))
        self.lbl_Patient1_DextroseWeight.setText(_translate("MainWindow", "Dextrose Weight: 500mg"))
        self.lbl_Patient1_Percent.setText(_translate("MainWindow", "50%"))
        self.lbl_Patient2.setText(_translate("MainWindow", "Patient 2"))
        self.lbl_Patient2_DextroseWeight.setText(_translate("MainWindow", "Dextrose Weight: 600mg"))
        self.lbl_Patient2_Percent.setText(_translate("MainWindow", "60%"))
        self.lbl_Title.setText(_translate("MainWindow", "DEXTROSE MONITOR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
